# Generated by Django 5.1 on 2024-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
